name: .NET Framework 4.5 Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: Windows

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe C:\Windows\System32\actions-runner\_work\SampleASPFramework45\SampleASPFramework45\SampleASPFramework45.sln /p:Configuration=Release /p:DeployOnBuild=true -verbosity:Diagnostic
