name: .NET Framework 4.5 Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-version: 'v4.5'

      - name: Build
        run: msbuild SampleASPFramework45.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile -verbosity:Diagnostic

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: netframework:${{ github.run_id }}
          path: PrivilegesDataController/bin/release
